# https://coolors.co/palettes/popular/7%20colors
.\create-icons.ps1 -Name SlateTeal      -Count 4 -Mode Number -BGColor "#264653" -FGColor "#ffffff"
.\create-icons.ps1 -Name DarkTeal       -Count 4 -Mode Number -BGColor "#287271" -FGColor "#ffffff"
.\create-icons.ps1 -Name SoftTurquise   -Count 4 -Mode Number -BGColor "#2a9d8f" -FGColor "#ffffff"
.\create-icons.ps1 -Name Sage           -Count 4 -Mode Number -BGColor "#8ab17d" -FGColor "#ffffff"
.\create-icons.ps1 -Name Sand           -Count 4 -Mode Number -BGColor "#e9c46a" -FGColor "#000000"
.\create-icons.ps1 -Name Peach          -Count 4 -Mode Number -BGColor "#f4a261" -FGColor "#000000"
.\create-icons.ps1 -Name Coral          -Count 4 -Mode Number -BGColor "#e76f51" -FGColor "#ffffff"
.\create-icons.ps1 -Name SlateTeal      -Count 4 -Mode Letter -BGColor "#264653" -FGColor "#ffffff"
.\create-icons.ps1 -Name DarkTeal       -Count 4 -Mode Letter -BGColor "#287271" -FGColor "#ffffff"
.\create-icons.ps1 -Name SoftTurquise   -Count 4 -Mode Letter -BGColor "#2a9d8f" -FGColor "#ffffff"
.\create-icons.ps1 -Name Sage           -Count 4 -Mode Letter -BGColor "#8ab17d" -FGColor "#ffffff"
.\create-icons.ps1 -Name Sand           -Count 4 -Mode Letter -BGColor "#e9c46a" -FGColor "#000000"
.\create-icons.ps1 -Name Peach          -Count 4 -Mode Letter -BGColor "#f4a261" -FGColor "#000000"
.\create-icons.ps1 -Name Coral          -Count 4 -Mode Letter -BGColor "#e76f51" -FGColor "#ffffff"