# https://coolors.co/palettes/popular/7%20colors
.\create-icons.ps1 -Name SlateTeal      -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#264653" -FGColor "#ffffff"
.\create-icons.ps1 -Name DarkTeal       -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#287271" -FGColor "#ffffff"
.\create-icons.ps1 -Name SoftTurquise   -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#2a9d8f" -FGColor "#ffffff"
.\create-icons.ps1 -Name Sage           -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#8ab17d" -FGColor "#ffffff"
.\create-icons.ps1 -Name Sand           -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#e9c46a" -FGColor "#000000"
.\create-icons.ps1 -Name Peach          -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#f4a261" -FGColor "#000000"
.\create-icons.ps1 -Name Coral          -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#e76f51" -FGColor "#ffffff"
.\create-icons.ps1 -Name SlateTeal      -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#264653" -FGColor "#ffffff"
.\create-icons.ps1 -Name DarkTeal       -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#287271" -FGColor "#ffffff"
.\create-icons.ps1 -Name SoftTurquise   -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#2a9d8f" -FGColor "#ffffff"
.\create-icons.ps1 -Name Sage           -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#8ab17d" -FGColor "#ffffff"
.\create-icons.ps1 -Name Sand           -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#e9c46a" -FGColor "#000000"
.\create-icons.ps1 -Name Peach          -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#f4a261" -FGColor "#000000"
.\create-icons.ps1 -Name Coral          -Mode Custom -CustomSymbols "1,2,3,4,A,B,C,D,M,P,Q,T" -BGColor "#e76f51" -FGColor "#ffffff"